### PR TITLE
feat: move to main as the default branch

### PR DESCRIPTION
**Pull request by ernestojeda**
Initial review to get ready for the master --> main conversion. Let me know if I missed anything.

Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Sandbox Testing
Test Links :

### CODE REVIEW

**Comment by soda480** [comment]
is it possible to functionally test this change against sample-service?  creating a branch called `main` on sample-service and building it using the changes in this branch?

**Review by cjoyv — APPROVED** [review]
LGTM

**Comment by ernestojeda** [comment]
@soda480 Sample service test running now with this PR: https://github.com/edgexfoundry/sample-service/pull/123

**Review by bill-mahoney — APPROVED** [review]
LGTM!

**Pull request merged**
