### PR TITLE
refactor: Unit tests for edgeXDocGeneration

### PR DESCRIPTION
**Pull request by cjoyv**
refactor(tests): Unit tests for edgeXDocGeneration
Signed-off-by: Chinu Joy <chinu.joy@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Sandbox Testing
Test Links :

### CODE REVIEW

**Review by soda480 — DISMISSED** [review]
LGTM - I need to brush up on non-JenkinsPipelineSpecification unit tests.

**Comment by soda480** [comment]
@cjoyv  How are these unit tests invoked?

**Comment by cjoyv** [comment]
> @cjoyv How are these unit tests invoked?

@soda480 These unit tests are running along with other unit tests when we run gradle test

**Review by bill-mahoney — DISMISSED** [review]
LGTM

**Review by ernestojeda — APPROVED** [review]
LGTM

**Pull request merged**
