### PR TITLE
feat: add hanoi to valid release stream

### PR DESCRIPTION
**Pull request by bill-mahoney**
Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Sandbox Testing
Test Links :

### CODE REVIEW

**Review by soda480 — CHANGES_REQUESTED** [review]
Can you update the respective unit test please, in edgeXSpec.

**Comment by bill-mahoney** [comment]
@soda480  👍

**Review by ernestojeda — APPROVED** [review]
LGTM

**Review by soda480 — APPROVED** [review]
LGTM

**Pull request merged**
