### PR TITLE
feat: only fail stage artifact stage if possible to build artifact

### PR DESCRIPTION
**Pull request by bill-mahoney**
Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Added labels
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:
#326 
## Sandbox Testing
Test Links :
Functional Testing Results:
Releasing repository with no Jenkinsfile i.e. 'tag-only' release: [Link](https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/PR-133/9/pipeline/183)
image

Releasing repository with Jenkinsfile (Success): [Link](https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/PR-133/12/pipeline)
image

Releasing repository with Jenkinsfile (Normal Failure): [Link](https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/PR-133/11/pipeline)
image

Prior behavior of a 'tag-only' release was a build failure: [edgex-taf tag for Hanoi-dot](https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/release/51/pipeline/333)
image

## Are there any new imports or modules? If so, what are they used for and why?
No

### CODE REVIEW

**Review by ernestojeda — APPROVED** [review]
LGTM

**Review by cjoyv — APPROVED** [review]
LGTM

**Review by soda480 — APPROVED** [review]
Very nice.

**Comment by jamesrgregg** [comment]
Thanks for the test results!
LGTM

**Review by jamesrgregg — APPROVED** [review]

**Pull request merged**
